# Generated by Django 2.2.1 on 2019-05-06 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='PricelistProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('pricelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t190506.Pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t190506.Product')),
            ],
            options={
                'unique_together': {('pricelist', 'product')},
            },
        ),
    ]
